### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by staltz** [ssbc/scuttle-testbot#3]
Hey @pietgeursen, could you release a new version for this package? I'm using it and it's helpful, but 1.1.5 has a bug with how it sets `keys` based on `opts.keys`.
Thanks :)

**Comment by pietgeursen** [comment]
Hi @staltz,
I'm keen to help but I need a better bug description than that.
I'm looking at the code but nothing leaps out at me...

**Comment by pietgeursen** [comment]
Oh woops, I see what you mean.
I hadn't released the latest commit.
Published 1.1.6
